export const announcements = [
	{
		id: 1,
		label: "FREE SHIPPING",
		text: "Free shipping on all orders above ₹2,500",
		cta: "Shop Now",
		accent: "#1a1a1a",
	},
	{
		id: 2,
		label: "NEW ARRIVAL",
		text: "Ganesh Murti collection now live — limited stock",
		cta: "Explore",
		accent: "#1a1a1a",
	},
	{
		id: 3,
		label: "FESTIVE SALE",
		text: "Up to 20% off on all table lamps this week",
		cta: "Claim Deal",
		accent: "#1a1a1a",
	},
	{
		id: 4,
		label: "CUSTOM ORDER",
		text: "Design your own print — delivered in 5 days",
		cta: "Customize",
		accent: "#1a1a1a",
	},
];

export const categories = [
	{ id: "lamps", label: "Lamps", icon: "◎", count: "12 designs" },
	{ id: "home", label: "Home Decor", icon: "⬡", count: "20 designs" },
	{ id: "car", label: "Car Decor", icon: "◈", count: "8 designs" },
	{ id: "keychains", label: "Keychains", icon: "◇", count: "30 designs" },
	{ id: "devotional", label: "Devotional", icon: "❋", count: "15 designs" },
	{ id: "miniature", label: "Miniature", icon: "◉", count: "25 designs" },
	{ id: "custom", label: "Custom Order", icon: "✐", count: "Any design" },
];

export const heroSlides = [
	{
		id: 1,
		category: "Lamps",
		tag: "Trending",
		name: "Orēa Curlé",
		subtitle: "Modern 3D Printed Table Lamp",
		price: "₹3,000",
		desc: "Precision-printed in matte white. Ships in 5 days.",
		cta: "Shop Lamps",
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
		stat: [
			{ v: "22 cm", l: "Height" },
			{ v: "E27", l: "Bulb" },
			{ v: "4.8★", l: "Rating" },
		],
	},
	{
		id: 2,
		category: "Devotional",
		tag: "Bestseller",
		name: "Ganesh Murti",
		subtitle: "Intricately Printed Sacred Idol",
		price: "₹1,200",
		desc: "Resin-coated finish. Crafted with 0.1mm precision.",
		cta: "Shop Devotional",
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
		stat: [
			{ v: "15 cm", l: "Height" },
			{ v: "Resin", l: "Finish" },
			{ v: "5.0★", l: "Rating" },
		],
	},
	{
		id: 3,
		category: "Miniature",
		tag: "New Arrival",
		name: "Eiffel 1:500",
		subtitle: "Architectural Scale Model",
		price: "₹1,500",
		desc: "Obsessively detailed. Perfect for collectors.",
		cta: "Shop Miniatures",
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
		stat: [
			{ v: "18 cm", l: "Height" },
			{ v: "0.1mm", l: "Detail" },
			{ v: "4.8★", l: "Rating" },
		],
	},
	{
		id: 4,
		category: "Car Decor",
		tag: "Popular",
		name: "Dash Totem",
		subtitle: "Bespoke Dashboard Ornament",
		price: "₹550",
		desc: "Clip-fit base. UV-resistant filament.",
		cta: "Shop Car Decor",
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
		stat: [
			{ v: "8 cm", l: "Size" },
			{ v: "Clip-fit", l: "Install" },
			{ v: "4.7★", l: "Rating" },
		],
	},
	{
		id: 5,
		category: "Custom Order",
		tag: "Limited Slots",
		name: "Your Idea, Printed",
		subtitle: "Fully Custom 3D Prints",
		price: "From ₹800",
		desc: "Upload a design. We print and deliver in 5–7 days.",
		cta: "Start Custom",
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
		stat: [
			{ v: "5–7d", l: "Delivery" },
			{ v: "Any", l: "Design" },
			{ v: "100%", l: "Satisfaction" },
		],
	},
	{
		id: 6,
		category: "Keychains",
		tag: "Fan Favourite",
		name: "Geo Prism",
		subtitle: "Miniature Geometric Keychain",
		price: "₹280",
		desc: "Lightweight resin. 30+ designs. Custom engraving.",
		cta: "Shop Keychains",
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
		stat: [
			{ v: "4 cm", l: "Size" },
			{ v: "Resin", l: "Material" },
			{ v: "4.9★", l: "Rating" },
		],
	},
];

export type Product = {
	id: number;
	name: string;
	cat: string;
	price: string;
	tag: string;
	rating: string;
	reviews: number;
	img: string;
};

export const topSelling: Product[] = [
	{
		id: 1,
		name: "Orēa Curlé Lamp",
		cat: "Lamps",
		price: "₹3,000",
		tag: "Bestseller",
		rating: "4.8",
		reviews: 142,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 2,
		name: "Ganesh Murti",
		cat: "Devotional",
		price: "₹1,200",
		tag: "Top Rated",
		rating: "5.0",
		reviews: 89,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 3,
		name: "Geo Prism Keychain",
		cat: "Keychains",
		price: "₹280",
		tag: "Popular",
		rating: "4.9",
		reviews: 210,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 4,
		name: "Eiffel 1:500",
		cat: "Miniature",
		price: "₹1,500",
		tag: "New",
		rating: "4.8",
		reviews: 54,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 5,
		name: "Hexia Wall Panel",
		cat: "Home Decor",
		price: "₹1,800",
		tag: "Trending",
		rating: "4.7",
		reviews: 67,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 6,
		name: "Dash Totem",
		cat: "Car Decor",
		price: "₹550",
		tag: "Popular",
		rating: "4.7",
		reviews: 98,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 7,
		name: "Petalo Vase",
		cat: "Home Decor",
		price: "₹2,200",
		tag: "Limited",
		rating: "4.9",
		reviews: 33,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 8,
		name: "Lunē Dome Lamp",
		cat: "Lamps",
		price: "₹4,200",
		tag: "Limited",
		rating: "4.8",
		reviews: 21,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
];

export const trendingProducts: Product[] = [
	{
		id: 1,
		name: "Volta Arc Lamp",
		cat: "Lamps",
		price: "₹3,800",
		tag: "New",
		rating: "4.9",
		reviews: 18,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 2,
		name: "Tiny Mantra Tag",
		cat: "Keychains",
		price: "₹350",
		tag: "Trending",
		rating: "4.8",
		reviews: 76,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 3,
		name: "Dragon Keep",
		cat: "Miniature",
		price: "₹2,800",
		tag: "New",
		rating: "5.0",
		reviews: 12,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 4,
		name: "Diya Stand",
		cat: "Devotional",
		price: "₹680",
		tag: "Seasonal",
		rating: "4.9",
		reviews: 44,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 5,
		name: "Vent Bloom",
		cat: "Car Decor",
		price: "₹320",
		tag: "Popular",
		rating: "4.6",
		reviews: 130,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 6,
		name: "Rova Shelf Clip",
		cat: "Home Decor",
		price: "₹650",
		tag: "Trending",
		rating: "4.7",
		reviews: 55,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 7,
		name: "Om Plaque",
		cat: "Devotional",
		price: "₹950",
		tag: "New",
		rating: "4.8",
		reviews: 29,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 8,
		name: "City Block Set",
		cat: "Miniature",
		price: "₹3,400",
		tag: "Limited",
		rating: "5.0",
		reviews: 9,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
];

export const youMayLike: Product[] = [
	{
		id: 1,
		name: "Bloom Tag",
		cat: "Keychains",
		price: "₹420",
		tag: "Limited",
		rating: "4.8",
		reviews: 38,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 2,
		name: "Name Plaque",
		cat: "Custom",
		price: "From ₹800",
		tag: "Popular",
		rating: "4.9",
		reviews: 62,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 3,
		name: "Wheel Crest",
		cat: "Car Decor",
		price: "₹780",
		tag: "New",
		rating: "4.7",
		reviews: 19,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 4,
		name: "Hexia Wall Panel",
		cat: "Home Decor",
		price: "₹1,800",
		tag: "Trending",
		rating: "4.7",
		reviews: 41,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 5,
		name: "Portrait Bust",
		cat: "Custom",
		price: "From ₹3,500",
		tag: "New",
		rating: "5.0",
		reviews: 7,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
	{
		id: 6,
		name: "Diya Stand",
		cat: "Devotional",
		price: "₹680",
		tag: "Seasonal",
		rating: "4.9",
		reviews: 44,
		img: "https://i.pinimg.com/736x/ef/4a/fb/ef4afb6c44b3ce31a3778e4409db8b2c.jpg",
	},
];

export const reels = [
	{
		id: 1,
		user: "@priya_home",
		label: "Living room glow-up",
		likes: "4.2k",
		views: "28k",
	},
	{
		id: 2,
		user: "@rahul.decor",
		label: "Ganesh Murti unboxing",
		likes: "6.1k",
		views: "51k",
	},
	{
		id: 3,
		user: "@sneha.crafts",
		label: "My 3D keychain collection",
		likes: "2.8k",
		views: "19k",
	},
	{
		id: 4,
		user: "@ankit3d",
		label: "Eiffel on my study desk",
		likes: "3.5k",
		views: "33k",
	},
	{
		id: 5,
		user: "@home.by.nisha",
		label: "Night lamp vibes 🌙",
		likes: "7.4k",
		views: "62k",
	},
];

export const tagColors: Record<string, { bg: string; text: string }> = {
	Bestseller: { bg: "#fef3c7", text: "#92400e" },
	"Top Rated": { bg: "#fef3c7", text: "#92400e" },
	Popular: { bg: "#f3f4f6", text: "#374151" },
	New: { bg: "#dcfce7", text: "#15803d" },
	"New Arrival": { bg: "#dcfce7", text: "#15803d" },
	Trending: { bg: "#ede9fe", text: "#5b21b6" },
	Limited: { bg: "#fee2e2", text: "#991b1b" },
	"Fan Favourite": { bg: "#fef3c7", text: "#92400e" },
	Seasonal: { bg: "#fdf4ff", text: "#7e22ce" },
	"Top Seller": { bg: "#fef3c7", text: "#92400e" },
	"Limited Slots": { bg: "#fee2e2", text: "#991b1b" },
};

export const fadeUp = {
	hidden: { opacity: 0, y: 22 },
	show: {
		opacity: 1,
		y: 0,
		transition: { duration: 0.5, ease: [0.22, 1, 0.36, 1] },
	},
};

export const stagger = {
	hidden: {},
	show: { transition: { staggerChildren: 0.08, delayChildren: 0.05 } },
};